#cloud-config
hostname: CoreOS-Master
coreos:
  update:
    reboot-strategy: off
  etcd2:
    name: core-01
    initial-advertise-peer-urls: http://10.15.15.10:2380
    initial-cluster-token: CoreOS-Master_etcd
    initial-cluster: CoreOS-Master=http://10.15.15.10:2380
    initial-cluster-state: new
    listen-peer-urls: http://0.0.0.0:2380,http://0.0.0.0:7001
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    advertise-client-urls:  http://0.0.0.0:2379,http://0.0.0.0:4001
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: docker-tcp.socket
      command: start
      enable: true
      content: |
        [Unit]
        Description=Docker Socket for the API

        [Socket]
        ListenStream=2375
        BindIPv6Only=both
        Service=docker.service

        [Install]
        WantedBy=sockets.target
    - name: docker.service
      command: start
      drop-ins:
        - name: 50-insecure-registry.conf
          content: |
            [Unit]
            [Service]
            Environment=DOCKER_OPTS='--insecure-registry="0.0.0.0/0"'
    - name: static.network  
      content: |  
        [Match]  
        Name=ens33

        [Network]  
        Address=10.15.15.10/24  
        Gateway=10.15.15.2  
        DNS=10.15.15.2  
users:

        - name: core

          ssh-authorized-keys:

                - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAl3hRqo9K2M3cny/5qGm11HErGgZBmwFHv3ZePl/bBRULndo0KBpPuHnzmCmO4yxO3t2USoIMPa9DWdOsiSq3H+apf0sfXEQsMhRYS2QkcsCQqWO0Iba4DQKjD5Garp0ioTdZX6kn+MtF2i3AqjW6XfgDGnGGaaSneA4899Cr46a8LiKw3YANB/6mUar93lbnG8L0pvdBmY8VO2u/HUX2X5mkM91FR2gk4JqPRUI87r2Jr4Utka0VGrAp4pWPzdFecWyx/5D7/fioPE8eqCcwfn5b73aP7ZM/ciBZr6pD5oVnPuY3HVxRehx1PhpSm+L0foHHt6yx5FdlkZU3tylzRQ==
        - groups:
             - sudo
               - docker
